name: Create Unity Package

on:
  push:
    branches: [ master ]

jobs:
  zip_package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/upload-artifact@master
      with:
        path: |
          Assets/com.caeden117.curved-ui-utility
          !Assets/**/*.meta
        name: 'Curved UI Utility'
