name: Create Unity Package

on:
  push:
    branches: [ master ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/upload-artifact@master
      with:
        path: |
          Assets/com.caeden117.curved-ui-utility
          !*.meta
        name: 'Curved UI Utility'
